version: '3.2'

services:
  sensors:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: vessels_db
      PGDATABASETEST: vessels_db_test
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data/:z
